version: "3"

services:
  web-server:
    build:
      context: .
    container_name: web-app
    volumes:
      - ./:/home/node/app/src
    expose:
      - "8080"
    ports:
      - "8080:8080"
      - "9229:9229"
    command: yarn start:dev
    restart: always
    depends_on:
      - mongo

  mongo:
    container_name: mongo
    image: mongo:latest
    ports:
      - "27017:27017"